repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: uv run ruff
        language: system
        types: [python]
        args: [check, --fix, .]
        pass_filenames: false
      
      - id: pytest
        name: pytest
        entry: uv run pytest -xvs --cov-report term-missing --cov src/mcp_server_pacman tests
        language: system
        types: [python]
        pass_filenames: false
        always_run: true