name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install build dependencies
        run: uv pip install build

      - name: Build package
        run: uv run build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}